from django.urls import path
from . import inicio, usuarios, noticias, comentarios, views, grupo

urlpatterns = [
    path('', inicio.inicio, name='inicio'),
    path('verusuario', usuarios.ver, name='verusuario'),
    path('nueusuario', usuarios.nuevo, name='nueusuario'),
    path('createuser', usuarios.nuevo, name='createuser'),
    path('modusuario/<id>', usuarios.modificar, name='modusuario'),
    path('borusuario/<id>', usuarios.borrar, name='borusuario'),
    path('add_noti', noticias.agregar_noticia, name='addnoti'),
    path('ver_noti', noticias.ver_noticias, name='vernoti'),
    path('full_noti/<int:noticia_id>', noticias.ver_noticia_completa, name='fullnoti'),
    path('acceder', inicio.acceder, name='acceder'),
    path('create', inicio.create, name='create'),
    path('salir', inicio.salir, name='salir'),
    path('enviar_comentario/<int:noticia_id>', comentarios.enviar_comentario, name='enviar_comentario'),
    path('elim_comentario/<int:comentario_id>', comentarios.elim_comentario, name='elim_comentario'),
    path('pass_comentario/<int:comentario_id>', comentarios.pass_comentario, name='pass_comentario'),
    path('listanoticias', views.NoticiasAPILista.as_view(), name='listanoticias'),
    path('listanoticias/<int:id>', views.NoticiasAPIDetalle.as_view(), name='detallenoticias'),
    path('listagrupos', views.GruposAPILista.as_view(), name='listagrupos'),
    path('nuevogrupo', views.GruposAPINuevo.as_view(), name='nuevogrupo'),
    path('registro/', views.UsuarioRegistroAPI.as_view(), name='usuario_registro'),
    path('login/', views.UsuarioLoginAPI.as_view(), name='usuario_login'),
    path('noticias/<int:noticia_id>/comentarios/', views.PublicarComentarioAPI.as_view(), name='publicar_comentario'),
    path('ver_grupos/', grupo.ver_grupos, name='ver_grupos'),
    path('nuevo_grupo/', grupo.nuevo_grupo, name='nuevo_grupo'),
    path('modificar_grupo/<int:id>/', grupo.modificar_grupo, name='modificar_grupo'),
    path('borrar_grupo/<int:id>/', grupo.borrar_grupo, name='borrar_grupo'),
    path('crear_usuario/', views.RegistrarUsuarioAPI.as_view(), name='crear_usuario'),
]